--Database used: livesql


CREATE TABLE ENROLLMENT(
    S_ID NUMBER(3) NOT NULL,
    CLASSNAME VARCHAR(50) NOT NULL,
    GRADE VARCHAR(1) NOT NULL
);

INSERT INTO ENROLLMENT
VALUES(123,'Synthesis algorithms', 'A');

INSERT INTO ENROLLMENT
VALUES(123,'EDM synthesis', 'B');

INSERT INTO ENROLLMENT
VALUES(123,'MIDI controllers', 'B');

INSERT INTO ENROLLMENT
VALUES(662,'Sound mixing', 'B');

INSERT INTO ENROLLMENT
VALUES(662,'EDM synthesis', 'A');

INSERT INTO ENROLLMENT
VALUES(662,'Electronic Music Fundamentals', 'A');

INSERT INTO ENROLLMENT
VALUES(662,'MIDI controllers', 'B');

INSERT INTO ENROLLMENT
VALUES(345,'MIDI controllers', 'A');

INSERT INTO ENROLLMENT
VALUES(345,'Electronic Music Fundamentals', 'B');

INSERT INTO ENROLLMENT
VALUES(345,'EDM synthesis', 'A');

INSERT INTO ENROLLMENT
VALUES(555,'EDM synthesis', 'B');

INSERT INTO ENROLLMENT
VALUES(555,'Electronic Music Fundamentals', 'B');

INSERT INTO ENROLLMENT
VALUES(213,'Electronic Music Fundamentals', 'A');

-- actual solution below

SELECT CLASSNAME, COUNT(S_ID) AS TOTAL
FROM ENROLLMENT
GROUP BY CLASSNAME
ORDER BY COUNT(S_ID) DESC;



