--Database used: livesql


CREATE TABLE INSTRUCTOR ( 
    INST_ID NUMBER NOT NULL, 
    INST_NAME VARCHAR(30) NOT NULL, 
    HOURLY_TEACHING_CHG NUMBER NOT NULL, 
    PRIMARY KEY (INST_ID) 
);


CREATE TABLE INSTRUCTOR_CLASSES( 
    CLASS_ID VARCHAR(6) NOT NULL, -- unique code for each cass (section) being taught 
    COURSE_NAME VARCHAR(30) NOT NULL, 
    INST_ID NUMBER NOT NULL, 
    CLASS_STRENGTH NUMBER NOT NULL, 
    PRIMARY KEY (CLASS_ID), 
    FOREIGN KEY (INST_ID) REFERENCES INSTRUCTOR (INST_ID) 
);

INSERT INTO INSTRUCTOR 
VALUES(1, 'Dan Brown', 55);

INSERT INTO INSTRUCTOR 
VALUES(2, 'Sophie Turner', 40);

INSERT INTO INSTRUCTOR 
VALUES(3, 'Matt Damon', 50);

INSERT INTO INSTRUCTOR 
VALUES(4, 'Chris Harris', 60);

INSERT INTO INSTRUCTOR_CLASSES 
VALUES ('EMF101','Electronic Music Fundamentals',1,25);

INSERT INTO INSTRUCTOR_CLASSES 
VALUES ('EDM101','EDM synthesis',1,20);

INSERT INTO INSTRUCTOR_CLASSES 
VALUES ('SYN101','Synthesis algorithms',2,18);

INSERT INTO INSTRUCTOR_CLASSES 
VALUES ('SMX101','Sound mixing',2,20);

INSERT INTO INSTRUCTOR_CLASSES 
VALUES ('SYN102','Synthesis algorithms',3,12);

INSERT INTO INSTRUCTOR_CLASSES 
VALUES ('EMF102','Electronic Music Fundamentals',4,28);

INSERT INTO INSTRUCTOR_CLASSES 
VALUES ('MDC101','MIDI controllers',4,25);

INSERT INTO INSTRUCTOR_CLASSES 
VALUES ('EDM102','EDM synthesis',4,20);


SELECT MAX(SUM(CLASS_STRENGTH*HOURLY_TEACHING_CHG*0.1)) as Max_Bonus 
FROM INSTRUCTOR_CLASSES ic 
JOIN INSTRUCTOR ins 
ON ins.INST_ID = ic.INST_ID 
GROUP BY ic.INST_ID;


