--Database used: livesql


CREATE TABLE PROJECTS(
    PID VARCHAR(4) NOT NULL,
    Step NUMBER NOT NULL,
    Status CHAR NOT NULL
);

INSERT INTO PROJECTS
VALUES('P100',0,'C');

INSERT INTO PROJECTS
VALUES('P100',1,'W');

INSERT INTO PROJECTS
VALUES('P100',2,'W');

INSERT INTO PROJECTS
VALUES('P201',0,'C');

INSERT INTO PROJECTS
VALUES('P201',1,'C');

INSERT INTO PROJECTS
VALUES('P333',0,'W');

INSERT INTO PROJECTS
VALUES('P333',1,'W');

INSERT INTO PROJECTS
VALUES('P333',2,'W');

INSERT INTO PROJECTS
VALUES('P333',3,'W');

SELECT PID
FROM PROJECTS
WHERE Status = 'C'
GROUP BY PID
HAVING COUNT(*) = 1;

